### ISSUE TITLE
Error when generating cuda code using vecscatter

### ISSUE THREAD

**Issue by simple86** [CtopCsUtahEdu/bricklib#1] opened 2021-09-07 14:05 UTC
When I try to generate cuda code using vecscatter, I am facing the following error.
I run the command `# vecscatter 3axis.cu out.cu` in bricklib/stencils/
```/home/bricklib/stencils
In file included from /usr/include/c++/5/type_traits:35:0,
                 from /home/bricklib/include/brick.h:10,
                 from /home/bricklib/include/brick-cuda.h:9,
                 from stencils_cu.h:8,
                 from 3axis.cu:5:
/usr/include/c++/5/bits/c++0x_warning.h:32:2: error: #error This file requires compiler and library support for the ISO C++ 2011 standard. This support must be enabled with the -std=c++11 or -std=gnu++11 compiler options.
 #error This file requires compiler and library support \
  ^

3axis.cu 226
Traceback (most recent call last):
  File "/root/miniconda3/bin/vecscatter", line 4, in <module>
    __import__('pkg_resources').run_script('st==0.1', 'vecscatter')
  File "/root/miniconda3/lib/python3.8/site-packages/pkg_resources/__init__.py", line 650, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/root/miniconda3/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1446, in run_script
    exec(code, namespace, namespace)
  File "/root/miniconda3/lib/python3.8/site-packages/st-0.1-py3.8.egg/EGG-INFO/scripts/vecscatter", line 184, in <module>
    eval(call)
  File "<string>", line 1, in <module>
  File "/root/miniconda3/lib/python3.8/site-packages/st-0.1-py3.8.egg/EGG-INFO/scripts/vecscatter", line 150, in Brick
    backend = get_backend(vec)
  File "/root/miniconda3/lib/python3.8/site-packages/st-0.1-py3.8.egg/EGG-INFO/scripts/vecscatter", line 83, in get_backend
    from st.codegen.backend import BackendAVX512, BackendAVX2, BackendScalar, BackendCUDA, BackendFlex, BackendSSE, \
ModuleNotFoundError: No module named 'st.codegen'
```

By the way, the Codegen Integeration guide page (https://github.com/CtopCsUtahEdu/bricklib/blob/r0.1) seems to be lost. I'll appreciate it a lot if someone can fix it. Thank you for attention.

**Comment by ztuowen** [comment] 2021-09-08 00:15
These are two different issues. 

The first issue is on your version of the compiler the default c++ standard is not c++11. You can add `-std=c++11` as suggested by the error message. In fact, c++14 is required per the `README.md`. So you should use `-std=c++14` at least.

The second issue is with the broken python install script. I have just pushed fixes to the *r0.1* branch. Can you check if it is working now?  However, note that installing the code generator as a library is not necessary. 

The CMake build script has the highest level of support (what we are using regularly). If you can check the `README.md` for how to build, most things should work as intended: both of these issues shouldn't appear. If you can elaborate on why CMake is not working on your system that would be most helpful.

I've also pushed some documentation just now which also contains the integration guide.

**Comment by simple86** [comment] 2021-09-09 08:46
Thank you for updating your code and docs. Everything goes well for me now.

**Comment by ztuowen** [comment] 2021-09-09 17:18
@simple86 We are preparing for a release with an installation script and out-of-tree references. If you wouldn't mind providing your usage scenarios resulting in CMake issues? 

We want to know if a) CMake is working as intended on as many systems as possible and collect the necessary changes we need to make and b) if we need to support other means of using this library.

**Comment by simple86** [comment] 2021-09-10 05:53
> @simple86 We are preparing for a release with an installation script and out-of-tree references. If you wouldn't mind providing your usage scenarios resulting in CMake issues?
> 
> We want to know if a) CMake is working as intended on as many systems as possible and collect the necessary changes we need to make and b) if we need to support other means of using this library.

Thst's great! 

I was trying to measure the performance of Brick for various stencils on GPU. By building with CMake as `ReadMe.md` says, I got a binary executable `cuda`, which tests `7pt` and `cond7pt` stencils. However, it's not easy to generate and run other stencils. I checked the code and setup `vecscatter`, expecting to generate code by running command `$vecscatter 3axis.cu out.cu`, but resulting in `module st.codegen not found` issue (fixed now). 

For now, as far as I know, I need to add a `.py` file for stencil discription, a `.cu` file for vecscatter replacing brick marco with computation code, a function call (like `d3pt7cu()`) in single/cuda.cpp, and need to add VSTARGET call in single/CMakeLists.txt. For example, I add the followings in single/CMakeLists.txt to run star2d5pt stencil.
 
```cmake
if (CMAKE_CUDA_COMPILER)
    # star2d5pt
    set(STAR2D5PT_INCLUDE_DIRS
            "${CMAKE_CUDA_TOOLKIT_INCLUDE_DIRECTORIES}"
            )
    VSTARGET(STAR2D5PT ../mytest/star2d5pt.cu ../mytest/star2d5pt-out.cu)
    add_executable(single-star2d5pt cuda.cpp ${VSTARGET_STAR2D5PT_OUTPUT})
    target_link_libraries(single-star2d5pt brickhelper)
    set_target_properties(single-star2d5pt
            PROPERTIES OUTPUT_NAME star2d5pt)
    target_include_directories(single-star2d5pt PUBLIC
            "${CMAKE_CUDA_TOOLKIT_INCLUDE_DIRECTORIES}"
            )
endif ()

```

After that, I can get an executable `star2d5pt` by `$make single-star2d5pt`.

Am I using it in the right way? Is there a better way to get what I want? I think it'll be great if the usage of the library could be easier.

Besides, the c++ standard warning is still there. I added `set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++14")` in ./CMakeLists.txt, but it seems not helpful.

P.S.
```
$cat /proc/version
Linux version 5.4.0-77-generic (buildd@lgw01-amd64-028) (gcc version 9.3.0 (Ubuntu 9.3.0-17ubuntu1~20.04)) #86-Ubuntu SMP Thu Jun 17 02:35:03 UTC 2021
$cmake --version
cmake version 3.14.5
```

**Comment by ztuowen** [comment] 2021-09-10 20:11
Thank you for your feedback. 

Yes, the CMake config is the intended way for building things in-tree. If you are trying to call vecscatter, calling it directly without installing also works: `python3 <path-to-vecscatter> ...params...`. This way saves you the trouble of setting up the miniconda.

I'll try to reproduce the issue regarding C++ standard. It is most likely caused by the software versions of 20.04 ubuntu. 

Since the c++11 thingy doesn't prevent code generation, I'll close this ticket.

**Closed as completed by ztuowen** 2021-09-10 20:11 UTC
